name: axelor

services:
  db:
    image: postgres:12.2
    container_name: educaflow
    environment:
      POSTGRES_USER: educaflow
      POSTGRES_PASSWORD: educaflow
      POSTGRES_DB: educaflow
    ports:
      - "5432:5432"
